name: quick_pay
description: A new Flutter application.

publish_to: 'none'

version: 1.0.8+9

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  http: ^0.13.5
  flutter_bloc: ^8.0.1
  pinput: ^2.2.19
  pin_code_fields: ^7.4.0
  fluttertoast: ^8.0.9
  carousel_slider: ^4.0.0-nullsafety.0
  razorpay_flutter: ^1.3.4

  animation_wrappers: ^3.0.0
  google_mobile_ads: ^0.13.2
  flutter_phoenix: ^1.0.0
  shared_preferences: ^2.0.13
  qr_code_scanner: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  flutter_html: ^2.2.1
#  image_picker: ^0.8.5
  image_picker: ^0.8.6
  # buy_this_app:
  #    git:
  #      url: git@gitlab.com:verbosetech-flutter/buy-this-app-package.git
  #      ref: c489910f

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/imgs/
    - assets/imgs/ecommerce/
    - assets/imgs/ecommerce/New folder/
    - assets/icons/
    - assets/icons/footer menu/
    - assets/icons/account/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf